name: Update README

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit README to trigger image refresh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README to refresh stats" || echo "No changes to commit"
          git push
